import '../styles/globals.css'
import Link from 'next/link'
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head'



function MyApp({ Component, pageProps }) {
  //return <Component {...pageProps} />
  const router = useRouter();
  //const[route, setRoute] = useState('')

  useEffect(() => {
  }, []);
  
  return(
    <>
      <Head>
        <title>Hirewise A.I.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css"></link>
      </Head>
    
      <Component {...pageProps}></Component>
    </>
  )
}

export default MyApp
